# -*- coding: utf-8 -*-
"""DaniqueJohnsonPinnock.RoshawnDewdney.RushonBrown-POS-ITT103-SP2026.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17WPICNc9oJsVbXoUwzgG7Dd7OCankTMS
"""

ITEM_DB = {
    "eggs": {"cost": 50.00, "qty_left": 10},
    "akmond milk": {"cost": 760.00, "qty_left": 65},
    "alkaline water": {"cost": 599.00, "qty_left": 160},
    "brown sugar": {"cost": 100.00, "qty_left": 75},
    "lasco": {"cost": 1900.00, "qty_left": 68},
    "boom": {"cost": 300.00, "qty_left": 19},
    "irish spring": {"cost": 97.00, "qty_left": 76},
    "cornflakes": {"cost": 900.00, "qty_left": 34},
    "taste cheese": {"cost": 1600.00, "qty_left": 68},
    "icool water": {"cost": 100.00, "qty_left": 85}
}
# Dictionary to track items in the current customer's order
CURRENT_ORDER = {}

def list_all_stock():
    print("\n=== Best Buy Retail Store ===")
    print(f"{'PRODUCT':<12} {'UNIT COST':<12} {'REMAINING':<10}")
    print("-" * 38)
    for prod, data in ITEM_DB.items():
        print(f"{prod.capitalize():<12} ${data['cost']:<12.2f} {data['qty_left']:<10}")
    print("-" * 38)
# Ensures valid input and updates stock levels.

def insert_purchase():
    list_all_stock()
    prod_name = input("\nProduct to purchase: ").strip().lower()
# Validate product existence
    if prod_name not in ITEM_DB:
        print("Product unavailable.")
        return

    try:
        how_many = int(input(f"Quantity of {prod_name.capitalize()}: "))
        if how_many <= 0:
    # Check for suffiecient stock

            print("Quantity must be positive.")
            return
        if how_many > ITEM_DB[prod_name]["qty_left"]:
            print("Insufficient stock. Only", ITEM_DB[prod_name]["qty_left"], "available.")
            return

        if prod_name in CURRENT_ORDER:
            CURRENT_ORDER[prod_name] += how_many
        else:
            CURRENT_ORDER[prod_name] = how_many

        ITEM_DB[prod_name]["qty_left"] -= how_many
        print(f"Added {how_many} x {prod_name.capitalize()}.")
        # Low stock warning

        if ITEM_DB[prod_name]["qty_left"] < 5:
            print(f"STOCK WARNING: Only {ITEM_DB[prod_name]['qty_left']} {prod_name.capitalize()} remaining.")

    except ValueError:
        print("Enter a valid whole number.")

def delete_purchase():
    if not CURRENT_ORDER:
        print("Order list is empty.")
        return

    print("\nCurrent order items:")
    for p in CURRENT_ORDER:
        print(" -", p.capitalize())

    prod_name = input("\nItem to remove: ").strip().lower()
  # Ensure the product is in the order

    if prod_name not in CURRENT_ORDER:
        print("Item not in order.")
        return

    try:
        remove_qty = int(input(f"Quantity to remove from {prod_name.capitalize()}: "))
        if remove_qty <= 0:
            print("Quantity must be positive.")
            return

        current = CURRENT_ORDER[prod_name]
  # If removing all or more than ordered, delete item from order
        if remove_qty >= current:
            ITEM_DB[prod_name]["qty_left"] += current
            del CURRENT_ORDER[prod_name]
            print(f"Removed all {prod_name.capitalize()}.")
        else:
            CURRENT_ORDER[prod_name] -= remove_qty
            ITEM_DB[prod_name]["qty_left"] += remove_qty
            print(f"Removed {remove_qty} x {prod_name.capitalize()}.")

    except ValueError:
        print("Enter a valid whole number.")

def list_order():
    if not CURRENT_ORDER:
        print("\nOrder list is empty.")
        return 0.0

    print("\n=== CURRENT ORDER ===")
    running_total = 0.0
    print(f"{'PRODUCT':<12} {'QTY':<6} {'COST':<8} {'SUBTOTAL':<10}")
    print("-" * 40)

    for prod, qty in CURRENT_ORDER.items():
        unit_cost = ITEM_DB[prod]["cost"]
        line = unit_cost * qty
        running_total += line
        print(f"{prod.capitalize():<12} {qty:<6} ${unit_cost:<8.2f} ${line:<10.2f}")

    print("-" * 40)
    print(f"Running total: ${running_total:.2f}")
    return running_total

def build_receipt(sub, disc, tx, grand, paid_amt, chg):
    print("\n" + "=" * 55)
    print(f"{'Best Buy Retail Store':^55}")
    print("=" * 55)
    print(f"{'PRODUCT':<18} {'QTY':<5} {'UNIT':<10} {'LINE':<12}")
    print("-" * 55)

    for prod, qty in CURRENT_ORDER.items():
        unit_cost = ITEM_DB[prod]["cost"]
        line = unit_cost * qty
        print(f"{prod.capitalize():<18} {qty:<5} ${unit_cost:<10.2f} ${line:<12.2f}")

    print("-" * 55)
    print(f"Subtotal ${sub:.2f}")
    print(f"Discount (5%) -${disc:.2f}")
    print(f"Sales Tax (10%) ${tx:.2f}")
    print(f"Grand Total ${grand:.2f}")
    print(f"Paid ${paid_amt:.2f}")
    print(f"Change ${chg:.2f}")
    print("\nTHANK YOU FOR SHOPPING WITH US!")
    print("=" * 55)

def complete_transaction():
    if not CURRENT_ORDER:
        print("Cannot finalize an empty order.")
        return

    sub = list_order()
# Apply 5% discount if subtotal > $5000
    disc = 0.0
    if sub > 5000:
        disc = sub * 0.05
        print(f"\nDiscount applied: -${disc:.2f}")

    after_disc = sub - disc
    tx = after_disc * 0.10
    grand = after_disc + tx

    print(f"\nSubtotal: ${sub:.2f}")
    print(f"Discount: -${disc:.2f}")
    print(f"Tax: ${tx:.2f}")
    print(f"Total: ${grand:.2f}")
    print("=" * 40)
# Loop until valid payyment entered
    while True:
        try:
            paid_amt = float(input("Customer payment: $"))
            if paid_amt < grand:
                print("Payment insufficient.")
            else:
                chg = paid_amt - grand
                print(f"Change due: ${chg:.2f}")

            build_receipt(sub, disc, tx, grand, paid_amt, chg)
    # Clear the current order for transaction

            CURRENT_ORDER.clear()
            break
        except ValueError:
            print("Enter a valid amount.")
#

def run_system():
    print("\nBest Buy Retail Store  - SALES TERMINAL")
    while True:
        print("\n" + "=" * 40)
        print("1. Add product")
        print("2. Remove product")
        print("3. Show order")
        print("4. Finalize sale")
        print("5. Quit")
        print("=" * 40)

        pick = input("Option number: ").strip()
# Menu Navigation

        if pick == "1":
            insert_purchase()
        elif pick == "2":
            delete_purchase()
        elif pick == "3":
            list_order()
        elif pick == "4":
            complete_transaction()
        elif pick == "5":
            print("\nSession ended. Thank you.")
            break
        else:
            print("Invalid option.")
  # Run programme if script is executed directly

if __name__ == "__main__":
    run_system()

