# -*- coding: utf-8 -*-
"""JohnsonPinnock.Danique-POS-ITT103-SP2026.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12bgMNUfX-BWgHZCd64AZVwMxh7h7yr-2
"""

def display_menu ():
  """Print the main menu options."""
  print("\n"+"="*40)
  print("Welcome to UCC Market")
  print("="*40)
  print("1. Add item to cart")
  print("2. Remove item from cart")
  print("3. View cart")
  print("4. Checkout")
  print("5. View product catalog")
  print("6. Start new transaction")
  print("0. Exit")
  print("="*40)

def get_product_catalog():
  return {
      "Rice": {"price": 650.00, "stock": 10},
      "Parboiled Rice": {"price": 1300.00, "stock": 8},
      "Jerk Seasoning": {"price": 200.00, "stock": 15},
      "Salt": {"price": 150.00, "stock": 2},
      "Pepper": {"price": 150.00, "stock": 2},
      "Sugar": {"price": 300.00, "stock": 5},
      "Oil": {"price": 1200.00, "stock": 3},
      "Vegetable Oil": {"price": 1000.00, "stock": 4},
      "Vinegar": {"price": 500.00, "stock": 6},
      "Soy Sauce": {"price": 800.00, "stock": 7},
      "Coffee": {"price": 1500.00, "stock": 2},
      "Tea": {"price": 1200.00, "stock": 3},
      "Milk": {"price": 400.00, "stock": 10},
      "Yogurt": {"price": 350.00, "stock": 8},
      "Cheese": {"price": 1200.00, "stock": 5},
      "Butter": {"price": 1000.00, "stock": 6},

  }

def display_catalog(products):
   print("Product Catalog")
   print(f"{'#':<3} {'Name':<15} 'Price' (J$)':<12 {'Stock':<8}")
   print("="*40)
   for i, (name, details) in enumerate(products.items(), start=1):
    print(f"{i:<3} {name:<15} {details['price']:<12} {details['stock']:<8}")

def get_valid_quantity (prompt):
  while True:
    try:
      quantity = int(input(prompt))
      if quantity <= 0:
        print("Invalid. Quantity must be greater than 0.")
      else:
        return quantity
    except ValueError:
      print("Invalid input. Please enter a valid whole number.")

def add_items_to_cart(products, cart):
    name = input("Enter product name: ")
    if name not in products:
      print("Product not found in catalog")
      return


    available = products[name]["stock"]


    qty = get_valid_quantity(f"Enter quantity (available: {available}): ")

    if qty > available:
      print(f"Only {available}. Cannot add {qty}.")
      return # Exit if quantity is too high

    # If we reach here, qty is valid and can be added
    if name in cart:
        # Update the quantity of an existing item in the cart
        cart[name]["quantity"] += qty
    else:
        # Add a new item to the cart
        cart[name] = {
            "quantity": qty,
            "price": products[name]["price"]
        }
    # Update the stock in the product catalog
    products[name]["stock"] -= qty
    print(f"Added {qty} {name} to cart. Stock left: {products[name]['stock']}")

def remove_items_from_cart(cart):
  if not cart:
    print("Cart is empty.")
    return

  print("Cart Items:")
  for name in cart:
    print(f"{name}")

  name = input("Enter product name to remove: "). strip()
  if name not in cart:
    print("Product not found in cart")
    return

  qty_in_cart = cart[name]["quantity"]
  print(f"Quantity in cart: {qty_in_cart}x {name}")
  qty_to_remove = get_valid_quantity(f"Enter quantity to remove:")

  if qty_to_remove >= qty_in_cart:
    del cart[name]
    print(f"Removed {name} from cart.")
  else:
    cart[name]["quantity"] -= qty_to_remove
    print(f"Removed {qty_to_remove} x {name}. Remaining: {cart[name]['quantity']}")

def view_cart(cart):
  if not cart:
    print("Cart is empty.")
    return

  print("\n--- SHOPPING CART ---")
  print(f"{'Name':<15} {'Quantity':<6} {'Price':<12} {'Total' :<12}")
  print("="*50)

  subtotal = 0.0
  for name, item in cart.items():
      quantity = item["quantity"]
      unit_price = item["price"]
      total = qty * unit_price
      subtotal += total
      print(f"{name:<10} {qty} {unit_price: .2f} ${total: .2f}")

  print(f"Subtotal: ${subtotal:.2f}")
  return subtotal

def apply_discount(total, discount_rate=0.05) :
  tax = subtotal * tax_rate
  return subtotal, tax

def apply_discount(total, discount_rate=0.5):
  if total > 5000:
     final = total - total * discount_rate
     return final, discount
  return total, 0.0

def get_valid_payment(prompt, min_amount):
    while True:
         try:
              amount = float(input(prompt))
              if amount < min_amount:
                  print(f"Amount must be at least $ {min_amount:.2f}")
              else:
                  return amount
         except ValueError:
             print("Please enter a valid amount.")

def print_receipt(store_name, cart, tax, total, paid, change):
  print("="*50)
  print(f"        {store_name} RECEIPT")
  print("="*50)
  print("Item   QTY   Unit Price   Total")

  for name, item in cart.items():
      qty = item["quantity"]
      unit_price = item["price"]
      total = qty * unit_price
      print(f"{name:<10} {qty} {unit_price: .2f} ${total: .2f}")

  print(f"Subtotal: ${subtotal:.2f}")
  print(f"Tax: (10%): ${tax:.2f}")
  print(f"Total: ${total:.2f}")
  print(f"Paid: ${paid:.2f}")
  print(f"Change: ${change:.2f}")
  print("     THANK YOU FOR SHOPPING WITH US!")

def low_stock_alert(products, threshold=5):
    low_stock_items = [(name, info["stock"])
    for name, info in products.items() if info["stock"] <= threshold]

    if low_stock_items:
        print("Low Stock Alert:")
        for name, stock in low_stock:
          print(f" {name}: only {qty} left in stock!")

def start_new_transaction(products, cart):
    if not cart:
       print("Cart is empty. No transaction to start.")
       return
    confirm = input("Are you sure? (y/n): "). strip().lower()
    if confirm in ("y", "yes"):
        cart.clear()
        print("Transaction started. Cart is now empty.")